apiVersion: apps/v1
kind: Deployment
metadata:
  name: cupcake-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cupcake-service
  template:
    metadata:
      labels:
        app: cupcake-service
    spec:
      containers:
        - name: cupcake-service
          image: kornvipa1003/cupcake-service:latest
          ports:
            - containerPort: 8081
