apiVersion: v1
kind: Service
metadata:
  name: cupcake-service
spec:
  selector:
    app: cupcake-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: NodePort	
